### ISSUE TITLE
`lazi.auto` breaks some imports

### ISSUE THREAD

**Issue by sitbon** [sitbon/lazi#1]
Reproduce:
1. Use `lazi.auto`
2. See that some imports fail.
3. [Disable __spec__ attr override](https://github.com/sitbon/lazi/blob/30194d68bdb6fd3b6b36712469279e7ae56769cf/lazi/core/loader.py#L51).
4. See that some other imports fail.

```python
import lazi.auto
from geopandas import GeoDataFrame
```

```traceback
Traceback (most recent call last):
  File "...", line 15, in <module>
    from geopandas import GeoDataFrame
ImportError: cannot import name 'GeoDataFrame' from 'geopandas' (/.../geopandas/__init__.py)
```

After (3):

```python
import lazi.auto
from pandas.core.nanops import check_below_min_count
```

```traceback
Traceback (most recent call last):
  File "/.../pandas/core/arrays/sparse/array.py", line 15, in <module>
    from pandas.core.nanops import check_below_min_count
ImportError: cannot import name 'check_below_min_count' from 'pandas.core.nanops' (/.../pandas/core/nanops.py)
```

**Comment by sitbon** [comment]
Simpler case, maybe the same issue:

1. install `toolz`.
2.

```python
import lazi.auto
import tlz

print(tlz.__name__, file=sys.stderr)
print(tlz.curry, file=sys.stderr)  # Fails
```

**Comment by sitbon** [comment]
Ok, so it's actually pretty simple. In some cases, the expectation that a module will
be executed immediately is used to create import-related side effects. In the case of `toolz`, it employs an interesting (but perhaps not uncommon) form of package-level polymorphism to support enhanced versions.

#### `/.../site-packages/tlz/__init__.py`
```python
from . import _build_tlz
```
#### `_build_tlz.py`
```python
import ...

class TlzLoader:
    ...

tlz_loader = TlzLoader()
sys.meta_path.append(tlz_loader)
tlz_loader.exec_module(sys.modules['tlz'])
```

Here, `tlz` expects `_build_tlz` to set things up right away.

There are two approaches I can think of to prevent lazy loading from causing these kinds of problems:
- Use a `NO_HOOK` list in `conf`.
  - Upside: Easy to implement, low overhead.
  - Downside: Requires discovery via trial & error, normal usage and testing - full code coverage 
    becomes crucial.
- Inspect the source files to detect top level statements with side effects.
  - Upside: It will be as reliable as the parsing/scanning method.
  - Downside: A sufficiently advanced scanner might defeat the purpose of lazy loading.

I think the downsides of the first approach are more manageable until a potentially better solution is devised in the case of a global import hook.

I'll also be adding a helper function to make non-global usage a little easier, similar to what can be found in the `lazy-imports` package (side note: I really like their `try_import()` context manager method).

**Comment by sitbon** [comment]
Minor epiphany: Because I'm saving the loading stack, the loader can do something a little smarter.
- When a lazy module is finally loaded (Loader's exec_module called), check the stack of other modules to see if they contain the loading module. If so, load them as well.
  - Might make sense now for each StackRecord to have a list of these deps instead of 
    scanning all of StackRecord.RECORD.

This behavior should be relatively configurable, to either:
1. Always load dependent modules (likely default), or
2. Only recursively load for selected modules (to replace the no-hook list).
